include:
  - ../postgres/compose.yml

services:
  pgadmin4:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    container_name: saac-pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
