services:
  postgres:
    image: postgres:16.1
    container_name: saac-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
